[project]
name = "satdifuser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy==1.26.3",
    "diffusers==0.17.0",
    "torch==2.2.2",
    "torchvision==0.17.2",
    "accelerate==0.18.0",
    "transformers==4.40.0",
    "scikit-learn==1.5.2",
    "huggingface_hub==0.19.3",
    "h5py==3.11.0",
    "tensorboard",
    "wandb",
    "omegaconf",
    "matplotlib",
    "fvcore",
    "rasterio",
    "faiss-cpu",
]
